apiVersion: apps/v1         # especifica a versao da api para o recurso deployment
kind: Deployment            # define que este recurso eh um deployment
metadata:
  name: ticket-tool-frontend-deployment  # nome do deployment do frontend
spec:
  replicas: 1               # define 1 pod rodando para o frontend
  selector:
    matchLabels:
      app: ticket-tool-frontend  # seleciona pods com o label app=ticket-tool-frontend
  template:
    metadata:
      labels:
        app: ticket-tool-frontend  # aplica o label aos pods criados por este deployment
    spec:
      containers:
      - name: frontend        # nome do container no pod
        image: seu_usuario_dockerhub/ticket-tool-frontend:latest  # imagem docker usada
        ports:
          - containerPort: 3000   # porta interna do container onde a app frontend escuta
        env:
          - name: VITE_API_URL    # variavel de ambiente que aponta para a url da api
            value: "http://ticket-tool-api-service"  # url do service da api dentro do cluster
